### ISSUE TITLE
The current locale should be used as an metadata entry

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/SeoBundle#253]
I would suggest to add that to an extra PreController hook not directly in the ContentListener, cause we can use Symfony's locale instead of the content ones. That should normaly the same, but WE would make it useable for non CMF Content by separating it.

**Comment by ElectricMaxxx** [comment]
Btw: found that issue/bug while showing the generated metdata and alternate locale setting on a conference. Dome of the audience mentioned it.

**Comment by dbu** [comment]
this actually is a tricky question. but i also tend towards the request locale. otherwise /de/some-untranslated-article is identified as being english even when everything apart from the main content is german.

can we avoid another listener and simply inject the information through DI? maybe with the RequestStack?

**Comment by dbu** [comment]
@ElectricMaxxx this might be nice to do for the current release if possible. but if you don't have time in the next few days, rather release than wait ;-)

**Comment by ElectricMaxxx** [comment]
Will hopefully find some time wednessday morning in the train.
